version: '2.1'
services:
    mysql:
        build: ./db/docker
        environment:
            MYSQL_DATABASE: 'node_db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'mysql'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'nodedbtest'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'nodedbtest'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
         # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
         # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        healthcheck:
            test: 'exit 0'
    api-boilerplate:
        build: .
        depends_on:
            mysql:
                condition: service_healthy
        entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
        ports:
            - '4000:4000'
    client:
        build: ./client
        environment:
            - '3000:3000'
        expose: 
            - '3000'
        ports:
            - '4010:3000'
        volumes:
            - ./client/src:/srv/craapp/src
            - ./client/public:/srv/craapp/public
        links:
            - api-boilerplate
        command: npm start